AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DBName:
    Default: MyDatabase
    Type: String
  DBUser:
    NoEcho: 'true'
    Type: String
  DBPassword:
    NoEcho: 'true'
    Type: String
  DBAllocatedStorage:
    Default: 20
    Type: Number
  DBInstanceClass:
    Type: String
    Default: db.t2.small
  SubnetGroupName:
    Type: String
    Default: test-eks
  DBIdentifier:
    Type: String
  Subnets:
    Type: String
  VPCId:
    Type: String
  NodeGroupSecurityGroupId:
    Type: String

Resources:
  ESMLoungeTestDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: subnet for esm-lounge-eks
      DBSubnetGroupName: !Ref "SubnetGroupName"
      SubnetIds:
        Fn::Split:
          - ","
          - !Ref "Subnets"
      Tags:
        - Key: Name
          Value: test-eks

  DBEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref "VPCId"
      GroupDescription: "EC2 SecurityGroup for DB"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        SourceSecurityGroupId: !Ref "NodeGroupSecurityGroupId"

  DBSecurityGroup:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      GroupDescription: "RDS SecurityGroup for DB"
      EC2VpcId: !Ref "VPCId"
      DBSecurityGroupIngress:
        EC2SecurityGroupId: !Ref "DBEC2SecurityGroup"

  MasterDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref "DBName"
      DBInstanceIdentifier: !Ref "DBIdentifier"
      AvailabilityZone:
        Fn::Select:
        - '1'
        - Fn::GetAZs:
            Ref: AWS::Region
      AllocatedStorage: !Ref "DBAllocatedStorage"
      DBInstanceClass: !Ref "DBInstanceClass"
      Engine: MySQL
      EngineVersion: 5.7.26
      MasterUsername: !Ref "DBUser"
      MasterUserPassword: !Ref "DBPassword"
      DBSubnetGroupName: !Ref "ESMLoungeTestDBSubnetGroup"
      Tags:
      - Key: Name
        Value: Master Database
      VPCSecurityGroups:
      - !Ref "DBEC2SecurityGroup"
    DeletionPolicy: Snapshot

Outputs:
  DatabaseURL:
    Description: "database url for production"
    Value:
      !Join ["", ["mysql2://", !Ref "DBUser", ":", !Ref "DBPassword", "@", !GetAtt "MasterDB.Endpoint.Address", ":", !GetAtt "MasterDB.Endpoint.Port", "/", !Ref "DBName"]]
    Export:
      Name: !Sub "${AWS::Region}-${AWS::StackName}-DatabaseURL"
