---
- name: create stack
  cloudformation:
    stack_name: "eks-vpc"
    state: present
    template: cfs/amazon-eks-vpc-private-subnets.yml
    template_parameters:
      VpcBlock: 192.168.0.0/16
      PublicSubnet01Block: 192.168.0.0/18
      PublicSubnet02Block: 192.168.64.0/18
      PrivateSubnet01Block: 192.168.128.0/18
      PrivateSubnet02Block: 192.168.192.0/18
