---
- name: create stack
  cloudformation:
    stack_name: "esm-lounge-test-eks"
    state: present
    template: cfs/amazon-eks.yml
    template_parameters:
      VpcBlock: 192.168.0.0/16
      PublicSubnet01Block: 192.168.0.0/18
      PublicSubnet02Block: 192.168.64.0/18
      PrivateSubnet01Block: 192.168.128.0/18
      PrivateSubnet02Block: 192.168.192.0/18
      KeyName: eks_ecs_users
      NodeImageId: ami-0a67c71d2ab43d36f
      NodeInstanceType: t3.medium
      NodeAutoScalingGroupMinSize: 1
      NodeAutoScalingGroupMaxSize: 1
      NodeAutoScalingGroupDesiredCapacity: 1
      NodeVolumeSize: 20
      ClusterName: esm-lounge-test
      BootstrapArguments: ""
      NodeGroupName: node-group
