AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  VPCStackName:
    Type: String
    Default: esm-lounge-test-vpc

  ALBStackName:
    Type: String
    Default: esm-lounge-test-alb

  RDSStackName:
    Type: String
    Default: esm-lounge-test-rds

  ECSServiceName:
    Type: String
    Default: Web

  ImageUrl:
    Type: String
    Default: 938859087688.dkr.ecr.ap-northeast-1.amazonaws.com/esm-lounge-test:latest

  ContainerPort:
    Type: Number
    Default: 3000

  ContainerCpu:
    Type: Number
    Default: 256

  ContainerMemory:
    Type: Number
    Default: 512

  Path:
    Type: String
    Default: "/*"

  DesiredCount:
    Type: Number
    Default: 2

  SecretKeyBase:
    Type: String

Resources:

  TaskDefinitionMigrate:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: db-migrate
      Cpu: !Ref 'ContainerCpu'
      Memory: !Ref 'ContainerMemory'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn:
        Fn::ImportValue:
              !Join ['-', [!Ref "AWS::Region", !Ref 'ALBStackName', 'ECSTaskExecutionRole']]
      TaskRoleArn: !Ref "AWS::NoValue"
      ContainerDefinitions:
        - Name: !Ref 'ECSServiceName'
          Cpu: !Ref 'ContainerCpu'
          Memory: !Ref 'ContainerMemory'
          Image: !Ref 'ImageUrl'
          PortMappings:
            - ContainerPort: !Ref 'ContainerPort'
          Command:
            - bundle
            - exec
            - rails
            - db:migrate
          Environment:
            - Name: DATABASE_URL
              Value:
                Fn::ImportValue:
                  !Join ["-", [!Ref "AWS::Region", !Ref "RDSStackName", "DatabaseURL"]]
            - Name: RAILS_ENV
              Value: production
            - Name: RAILS_LOG_TO_STDOUT
              Value: "true"
            - Name: SECRET_KEY_BASE
              Value: !Ref "SecretKeyBase"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: true
              awslogs-group: "esm-lounge-test-migrate"
              awslogs-region: "ap-northeast-1"
              awslogs-stream-prefix: ecs

  TaskDefinitionWeb:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref 'ECSServiceName'
      Cpu: !Ref 'ContainerCpu'
      Memory: !Ref 'ContainerMemory'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn:
        Fn::ImportValue:
          !Join ['-', [!Ref "AWS::Region", !Ref 'ALBStackName', 'ECSTaskExecutionRole']]
      TaskRoleArn: !Ref "AWS::NoValue"
      ContainerDefinitions:
        - Name: !Ref 'ECSServiceName'
          Cpu: !Ref 'ContainerCpu'
          Memory: !Ref 'ContainerMemory'
          Image: !Ref 'ImageUrl'
          PortMappings:
            - ContainerPort: !Ref 'ContainerPort'
          Command:
            - bundle
            - exec
            - puma -C config/puma.rb
          Environment:
            - Name: DATABASE_URL
              Value:
                Fn::ImportValue:
                  !Join ["-", [!Ref "AWS::Region", !Ref "RDSStackName", "DatabaseURL"]]
            - Name: RAILS_ENV
              Value: production
            - Name: RAILS_LOG_TO_STDOUT
              Value: "true"
            - Name: SECRET_KEY_BASE
              Value: "60fa06ddd2d44881c44cde447d0450a144e98878f223bac44cb8e3c52036d01079b4db465358b6e0ae0ec9174b60d8796460ec99ae54a0a8952a546a8ac4e1f3"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: true
              awslogs-group: "esm-lounge-test-web"
              awslogs-region: "ap-northeast-1"
              awslogs-stream-prefix: ecs

  Service:
    Type: AWS::ECS::Service
    DependsOn:
      - "ALBListener"
      - "LoadBalancerRule"
    Properties:
      ServiceName: !Ref 'ECSServiceName'
      Cluster:
        Fn::ImportValue:
          !Join ['-', [!Ref "AWS::Region", !Ref 'ALBStackName', 'ClusterName']]
      LaunchType: "FARGATE"
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      DesiredCount: !Ref 'DesiredCount'
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: "DISABLED"
          SecurityGroups:
            - Fn::ImportValue:
                !Join ['-', [!Ref "AWS::Region", !Ref 'ALBStackName', 'FargateContainerSecurityGroup']]
          Subnets:
            - Fn::ImportValue:
                !Join ['-', [!Ref "AWS::Region", !Ref 'VPCStackName', 'PrivateSubnet0']]
            - Fn::ImportValue:
                !Join ['-', [!Ref "AWS::Region", !Ref 'VPCStackName', 'PrivateSubnet1']]
      TaskDefinition: !Ref 'TaskDefinitionWeb'
      LoadBalancers:
        - ContainerName: !Ref 'ECSServiceName'
          ContainerPort: !Ref 'ContainerPort'
          TargetGroupArn: !Ref 'TargetGroup'

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 6
      HealthCheckPath: "/hi"
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      TargetType: ip
      Name: !Ref 'ECSServiceName'
      Port: !Ref 'ContainerPort'
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId:
        Fn::ImportValue:
          !Join ['-', [!Ref "AWS::Region", !Ref 'VPCStackName', 'VPC']]

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - "TargetGroup"
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref "TargetGroup"
          Type: "forward"
      LoadBalancerArn:
        Fn::ImportValue:
          !Join ['-', [!Ref "AWS::Region", !Ref "ALBStackName", "LoadBalancer"]]
      Port: 80
      Protocol: HTTP

  LoadBalancerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - TargetGroupArn: !Ref 'TargetGroup'
          Type: 'forward'
      Conditions:
        - Field: path-pattern
          Values: [!Ref 'Path']
      ListenerArn:
        !Ref "ALBListener"
        # Fn::ImportValue:
        #   !Join ['-', [!Ref "AWS::Region", !Ref 'ALBStackName', 'ALBListener']]
      Priority: 1
