---
apiVersion: v1
kind: Service
metadata:
  name: rails
  labels:
    app: rails
spec:
  selector:
    app: rails
  type: LoadBalancer
  ports:
    - targetPort: 3000
      protocol: TCP
      port: 80
