---
- name: create stack
  cloudformation:
    stack_name: "eks-nodegroup"
    state: present
    template: cfs/amazon-eks-nodegroup.yaml
    template_parameters:
      KeyName: "{{ nodegroup.KeyName }}"
      NodeImageId: "{{ nodegroup.NodeImageId }}"
      NodeInstanceType: "{{ nodegroup.NodeInstanceType }}"
      BootstrapArguments: ""
      NodeAutoScalingGroupMinSize: "{{ nodegroup.NodeAutoScalingGroupMinSize }}"
      NodeAutoScalingGroupMaxSize: "{{ nodegroup.NodeAutoScalingGroupMaxSize }}"
      NodeAutoScalingGroupDesiredCapacity:  "{{ nodegroup.NodeAutoScalingGroupDesiredCapacity }}"
      NodeVolumeSize: "{{ nodegroup.NodeVolumeSize }}"
      ClusterName: "{{ nodegroup.ClusterName }}"
      BootstrapArguments: ""
      NodeGroupName: "{{ nodegroup.NodeGroupName }}"
      ClusterControlPlaneSecurityGroup: "{{ ControlPlaneEgressToNodeSecurityGroup }}"
      VpcId: "{{ nodegroup.VpcId }}"
      Subnets: "{{ nodegroup.Subnets }}"
